name: empay_test_project
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  go_router: ^10.2.0
  local_auth: ^2.1.7
  retrofit: ^4.0.1
  dio: ^5.3.2
  sentry_flutter: ^7.10.1
  freezed_annotation: ^2.4.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  freezed: ^2.4.2
  retrofit_generator: ^7.0.8
  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/core/utils/gen/

  integrations:
    flutter_svg: true

flutter:
  generate: true
  assets:
    - assets/icons/
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
